user_schema = {
    "id": "integer",
    "external_id": "string",
    "parent_id": "integer",
    "name": "string",
    "email": "string",
    "phone_number": "string",
    "phone": "string",
    "disabled": "boolean",
    "round_robin": "boolean",
    "campaign_phone_number": "string",
    "avatar_url": "string",
    "roles": "string",
    "permissions": "string",
    "timezone": "string",
    "local_timezone": "string",
    "last_login_at": "2025-06-20T17:45:23.070Z",
    "email_verified_at": "2025-06-20T17:45:23.070Z",
    "phone_verified_at": "2025-06-20T17:45:23.070Z",
    "created_at": "2025-06-20T17:45:23.070Z",
    "created_at_timestamp": "string",
    "updated_at": "2025-06-20T17:45:23.070Z",
    "deleted_at": "2025-06-20T17:45:23.070Z",
    "application_link": "string",
    "survey_review_link": "string",
    "shared_prospect_notifications": "string",
    "send_merge_notifications": "string",
    "enable_realtor_automation": "string",
    "must_change_password": "boolean",
    "internal_permissions": [
      "string"
    ],
    "business": "string",
    "token_limit": "integer",
    "token_usage": "integer",
    "notification_email": "string",
    "daily_email": "integer",
    "bam_logo_disabled": "integer",
    "campaign_name": "string",
    "nmls": "string"
}
